import Head from "next/head";
import Sidebar from "../components/Sidebar";
import ChatBubbleIcon from "@material-ui/icons/ChatBubble";
import styled from "styled-components";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>ChitChat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SidebarWrapper>
        <Sidebar />
      </SidebarWrapper>
      <HomeContainer id="MessageContainer">
        <ChatIcon />
        <p>No chat selected</p>
      </HomeContainer>
    </Container>
  );
}

const Container = styled.div`
  display: flex;
`;

const SidebarWrapper = styled.div`
  flex: 0.45;
  @media (max-width: 650px) {
    width: 100%;
    flex: 1;
  }
`;

const HomeContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  color: white;
  flex: 1;
  font-size: 1.4rem;
  @media (max-width: 650px) {
    width: 100%;
    display: none;
    flex: 0;
  }
`;

const ChatIcon = styled(ChatBubbleIcon)`
  &&& {
    font-size: 15rem;
  }
`;
